name: Docs
on:
  schedule:
    - cron: '29 15 * * *'
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
jobs:
  doc:
    name: Docs
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        rust:
        #- stable
        #- beta
        - nightly
    steps:
    - uses: actions/checkout@v4
      name: "Checkout"
    - uses: dtolnay/rust-toolchain@nightly
      with:
        profile: "minimal"
        toolchain: "${{ matrix.rust }}"
        override: true
        name: "Install Rust ${{ matrix.rust }}"
    - uses: "actions-rs/cargo@v1"
      with:
        command: "check"
      name: "Run `cargo check`"
    - uses: dtolnay/install@cargo-docs-rs
      name: "Install cargo docs-rs"
    - run: cargo docs-rs
      name: "Run `cargo docs-rs`"